### ISSUE TITLE
Seems broken with last update on Elgato Software

### ISSUE THREAD

**Issue by qlaffont** [rweich/streamdeck-ts#24]
Hello :),
I try to create a new extension and with the same code (who is working before), now my property fields are not saved.
I don't know why. Do you have the same issue (in dev mod or release mod) ?
If needed, I can provided code.

PS: I'm using your template @rweich thanks for it ! My project was working 5 months ago. Try to update no success.

**Comment by qlaffont** [comment]
No error at all durring debug. 

Repo: https://gitlab.com/qlaffont/exalty-lestudio-streamdeck-counter/-/tree/master

**Comment by rweich** [comment]
heya,

when you use `pi.setSettings(uuid, { [parameter]: value });` in `Propertyinspector.ts`, you always override everything with just one key/value pair. if you want so save multiple key/value pairs, you need to pass all of them every time.

so basically you need to keep track of the other settings, you've already set.
e.g.:
```
const settings: Record<string, unknown> = {};
const sendValueToPlugin = (value: string, parameter: string) => {
  settings[parameter] = value;
  pi.setSettings(uuid, settings);
};
```

and then the settings-keys when reading and writing are different.
changing
```
sendValueToPlugin(event?.target?.value, 'setCounterActionType');
```
to
```
sendValueToPlugin(event?.target?.value, 'counterActionType');
```
should fix that

**Comment by qlaffont** [comment]
I have make changes without working :/

**Comment by qlaffont** [comment]
PS: Finally it wasn't the only issue event change since :
```typescript
plugin.on('didReceiveSettings', (event) => {
  const settings = event.settings as Record<string, unknown>;
```
after
```typescript
plugin.on('didReceiveSettings', ({eventPayload}) => {
  const event = eventPayload.payload;
  const context = eventPayload.context;
  const settings = event.settings as Record<string, unknown>;

```

**Comment by rweich** [comment]
that doesn't seem right.
i'm not exposing eventPayload because the values in event point to the ones in eventPayload...
so `event.settings` should yield the same result as (the unexposed) `event.eventPayload.payload.settings`.

i do get errors with your Plugin.ts, but they seem related to uninitialized variables rather than the event object. and i guess i've got an old version of your codebase now anyways. seems you've set it private now.

i really don't want you to access that property directy and clutter your code with ts-ignores (which i guess you need to do that). so if you'd like, i can take another look at that.
